[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Optional: hübscherer Pfad /api/gemini
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200
